### ISSUE TITLE
执行AppOutPutMethodOrder Task报错

### ISSUE THREAD

**Issue by fantasyado** [zjw-swun/AppMethodOrder#37]
E:\workspace\IndiaCP\android>gradlew AOPMO --stacktrace
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
        at org.gradle.api.tasks.compile.JavaCompile.setDependencyCacheDir(JavaCompile.java:241)
        at com.android.build.gradle.tasks.factory.AndroidJavaCompile_Decorated.setDependencyCacheDir(Unknown Source
)
        at com.android.build.gradle.tasks.factory.JavaCompileConfigAction.execute(JavaCompileConfigAction.java:131)

        at com.android.build.gradle.tasks.factory.JavaCompileConfigAction.execute(JavaCompileConfigAction.java:39)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:142)
        at com.android.build.gradle.internal.TaskContainerAdaptor.create(TaskContainerAdaptor.java:59)
        at com.android.build.gradle.internal.scope.AndroidTaskRegistry.create(AndroidTaskRegistry.java:47)
        at com.android.build.gradle.internal.scope.AndroidTaskRegistry.create(AndroidTaskRegistry.java:89)
        at com.android.build.gradle.internal.TaskManager.createJavacTask(TaskManager.java:1102)

**Comment by zjw-swun** [comment]
@fantasyado 建议使用小工具
